### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by axellos162** [MetabobProject/metabob-vscode#24]
### Description

Cannot perform an analysis on VSCode.

Steps to reproduce:
- Call "Metabob: Analyze Document" from the command palette
- The analysis running icon should show up in the bottom left corner but it doesn't

**Comment by RishiHParmar** [comment]
+1
Following is the Metabob-Debug

```
Activating Metabob
Activated
Metabob: Starting Analysis for /Users/someproject/src/java/com/trial/Abcd.java
```

There is no further processing. Extensions setting are at Default with metabob backend.
